In [1]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

from data_utils import train_test_split

In [2]:
(df_train_X, train_y), (df_test_X, test_y) = train_test_split()

In [3]:
df_cat = df_train_X[['ocean_proximity']]
df_cat.head(10)

ocean_proximity
17606       <1H OCEAN
18632       <1H OCEAN
14650      NEAR OCEAN
3230           INLAND
3555        <1H OCEAN
19480          INLAND
8879        <1H OCEAN
13685          INLAND
4937        <1H OCEAN
4861        <1H OCEAN

In [4]:
ordinal_encoder = OrdinalEncoder()
encoded = ordinal_encoder.fit_transform(df_cat)
encoded[:10]

array([[0.],
       [0.],
       [4.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.]])

In [5]:
ordinal_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [6]:
one_hot_encoder = OneHotEncoder()
df_one_hot = one_hot_encoder.fit_transform(df_cat)
df_one_hot

<16512x5 sparse matrix of type '<class 'numpy.float64'>'
	with 16512 stored elements in Compressed Sparse Row format>

In [7]:
df_one_hot.toarray()

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [8]:
one_hot_dense_encoder = OneHotEncoder(sparse=False)
df_one_hot_dense = one_hot_dense_encoder.fit_transform(df_cat)
df_one_hot_dense

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [9]:
one_hot_dense_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]